services:
  - type: web
    name: telegram-bot
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    envVars:
      - key: BOT_TOKEN
        value: 8037607280:AAFgsRjj-D0gyZNGfqwn1hh6C443lNoP0OU
